"""Initial migration with all models

Revision ID: d431aff678d1
Revises: 
Create Date: 2026-01-04 19:25:52.079975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd431aff678d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_paywalled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('user_id', app.db.types.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('catchup_minutes', sa.Integer(), nullable=True),
    sa.Column('catchup_goal_met', sa.Boolean(), nullable=True),
    sa.Column('divein_minutes', sa.Integer(), nullable=True),
    sa.Column('recap_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_metric_date', 'daily_metrics', ['user_id', 'metric_date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_user_id'), 'daily_metrics', ['user_id'], unique=False)
    op.create_table('expert_notes',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('expert_id', app.db.types.UUID(), nullable=False),
    sa.Column('article_id', app.db.types.UUID(), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('expert_industry', sa.String(length=50), nullable=True),
    sa.Column('expert_specializations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expert_article', 'expert_notes', ['expert_id', 'article_id'], unique=True)
    op.create_index(op.f('ix_expert_notes_article_id'), 'expert_notes', ['article_id'], unique=False)
    op.create_index(op.f('ix_expert_notes_expert_id'), 'expert_notes', ['expert_id'], unique=False)
    op.create_table('recap_sessions',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('user_id', app.db.types.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('synthesis_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_week_start', 'recap_sessions', ['user_id', 'week_start'], unique=True)
    op.create_index(op.f('ix_recap_sessions_user_id'), 'recap_sessions', ['user_id'], unique=False)
    op.create_table('storyboards',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('headline_article_id', app.db.types.UUID(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['headline_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboards_industry'), 'storyboards', ['industry'], unique=False)
    op.create_index(op.f('ix_storyboards_specializations'), 'storyboards', ['specializations'], unique=False)
    op.create_table('time_logs',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('user_id', app.db.types.UUID(), nullable=False),
    sa.Column('ring_type', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ring_started', 'time_logs', ['user_id', 'ring_type', 'started_at'], unique=False)
    op.create_index(op.f('ix_time_logs_user_id'), 'time_logs', ['user_id'], unique=False)
    op.create_table('user_saved_articles',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('user_id', app.db.types.UUID(), nullable=False),
    sa.Column('article_id', app.db.types.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_article', 'user_saved_articles', ['user_id', 'article_id'], unique=True)
    op.create_index(op.f('ix_user_saved_articles_article_id'), 'user_saved_articles', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_saved_articles_user_id'), 'user_saved_articles', ['user_id'], unique=False)
    op.create_table('recap_questions',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('recap_session_id', app.db.types.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recap_session_id'], ['recap_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recap_questions_recap_session_id'), 'recap_questions', ['recap_session_id'], unique=False)
    op.create_table('storyboard_articles',
    sa.Column('storyboard_id', app.db.types.UUID(), nullable=False),
    sa.Column('article_id', app.db.types.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('storyboard_id', 'article_id')
    )
    op.create_index('idx_storyboard_article_id', 'storyboard_articles', ['article_id'], unique=False)
    op.create_table('user_not_relevant',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('user_id', app.db.types.UUID(), nullable=False),
    sa.Column('storyboard_id', app.db.types.UUID(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_storyboard', 'user_not_relevant', ['user_id', 'storyboard_id'], unique=True)
    op.create_index(op.f('ix_user_not_relevant_user_id'), 'user_not_relevant', ['user_id'], unique=False)
    op.create_table('recap_responses',
    sa.Column('id', app.db.types.UUID(), nullable=False),
    sa.Column('question_id', app.db.types.UUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_option', sa.String(length=100), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['recap_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recap_responses_question_id'), 'recap_responses', ['question_id'], unique=False)
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_recap_responses_question_id'), table_name='recap_responses')
    op.drop_table('recap_responses')
    op.drop_index(op.f('ix_user_not_relevant_user_id'), table_name='user_not_relevant')
    op.drop_index('idx_user_storyboard', table_name='user_not_relevant')
    op.drop_table('user_not_relevant')
    op.drop_index('idx_storyboard_article_id', table_name='storyboard_articles')
    op.drop_table('storyboard_articles')
    op.drop_index(op.f('ix_recap_questions_recap_session_id'), table_name='recap_questions')
    op.drop_table('recap_questions')
    op.drop_index(op.f('ix_user_saved_articles_user_id'), table_name='user_saved_articles')
    op.drop_index(op.f('ix_user_saved_articles_article_id'), table_name='user_saved_articles')
    op.drop_index('idx_user_article', table_name='user_saved_articles')
    op.drop_table('user_saved_articles')
    op.drop_index(op.f('ix_time_logs_user_id'), table_name='time_logs')
    op.drop_index('idx_user_ring_started', table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index(op.f('ix_storyboards_specializations'), table_name='storyboards')
    op.drop_index(op.f('ix_storyboards_industry'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index(op.f('ix_recap_sessions_user_id'), table_name='recap_sessions')
    op.drop_index('idx_user_week_start', table_name='recap_sessions')
    op.drop_table('recap_sessions')
    op.drop_index(op.f('ix_expert_notes_expert_id'), table_name='expert_notes')
    op.drop_index(op.f('ix_expert_notes_article_id'), table_name='expert_notes')
    op.drop_index('idx_expert_article', table_name='expert_notes')
    op.drop_table('expert_notes')
    op.drop_index(op.f('ix_daily_metrics_user_id'), table_name='daily_metrics')
    op.drop_index('idx_user_metric_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
